/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d1e7dd",
        "surface-container-low": "#111827",
        "inverse-surface": "#e7f8ef",
        "on-primary-fixed": "#03140e",
        "on-surface": "#e7f8ef",
        "outline-variant": "#25443a",
        "error-container": "#4f1117",
        "on-error": "#2b0408",
        "inverse-primary": "#047857",
        "tertiary-container": "#4b1118",
        "surface-bright": "#24342f",
        "surface-variant": "#1f2f2a",
        "surface-tint": "#34d399",
        "primary-container": "#064e3b",
        "on-tertiary-fixed": "#3a050a",
        "secondary": "#a7f3d0",
        "primary-fixed-dim": "#34d399",
        "on-tertiary": "#3a050a",
        "tertiary-fixed": "#fecdd3",
        "tertiary": "#fb7185",
        "tertiary-fixed-dim": "#fda4af",
        "secondary-container": "#12352b",
        "on-surface-variant": "#9bb8ad",
        "on-background": "#e7f8ef",
        "surface-container": "#0f1a18",
        "primary": "#34d399",
        "surface-container-high": "#17221f",
        "on-primary-container": "#bbf7d0",
        "surface-container-highest": "#1f2f2a",
        "on-primary-fixed-variant": "#065f46",
        "on-secondary-fixed-variant": "#164e3c",
        "error": "#fca5a5",
        "secondary-fixed-dim": "#99f6e4",
        "inverse-on-surface": "#07110e",
        "on-secondary-fixed": "#061a13",
        "on-primary": "#03140e",
        "on-secondary-container": "#b7f7df",
        "on-tertiary-container": "#ffe4e6",
        "on-tertiary-fixed-variant": "#9f1239",
        "on-secondary": "#082018",
        "on-error-container": "#fee2e2",
        "surface-container-lowest": "#050a08",
        "background": "#070f0c",
        "surface-dim": "#070f0c",
        "primary-fixed": "#6ee7b7",
        "outline": "#55756a",
        "surface": "#0b1310"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.5rem", "lg": "0.75rem", "xl": "1rem", "full": "9999px"},
    },
  },
  plugins: [],
}
