/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d4e4fa",
        "surface-container-low": "#131b2e",
        "inverse-surface": "#dae2fd",
        "on-primary-fixed": "#002113",
        "on-surface": "#dae2fd",
        "outline-variant": "#3c4a42",
        "error-container": "#93000a",
        "on-error": "#690005",
        "inverse-primary": "#006c49",
        "tertiary-container": "#ff7979",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "surface-tint": "#4edea3",
        "primary-container": "#10b981",
        "on-tertiary-fixed": "#410006",
        "secondary": "#b9c8de",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary": "#670211",
        "tertiary-fixed": "#ffdad8",
        "tertiary": "#ffb3b0",
        "tertiary-fixed-dim": "#ffb3b0",
        "secondary-container": "#39485a",
        "on-surface-variant": "#bbcabf",
        "on-background": "#dae2fd",
        "surface-container": "#171f33",
        "primary": "#4edea3",
        "surface-container-high": "#222a3d",
        "on-primary-container": "#00422b",
        "surface-container-highest": "#2d3449",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#39485a",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#b9c8de",
        "inverse-on-surface": "#283044",
        "on-secondary-fixed": "#0d1c2d",
        "on-primary": "#003824",
        "on-secondary-container": "#a7b6cc",
        "on-tertiary-container": "#740d18",
        "on-tertiary-fixed-variant": "#881d24",
        "on-secondary": "#233143",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#060e20",
        "background": "#0b1326",
        "surface-dim": "#0b1326",
        "primary-fixed": "#6ffbbe",
        "outline": "#86948a",
        "surface": "#0b1326"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
